import http from "node:http";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, resolve, basename, extname } from "node:path";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
const exec=promisify(execFile),root=resolve(import.meta.dirname,".."),frontend=join(root,"frontend"),data=join(frontend,"public/data"),images=join(frontend,"public/images/artworks"),page=join(import.meta.dirname,"index.html"),port=4174,previewPort=4173;
const npmCommand=process.platform==="win32"?"npm.cmd":"npm";
const preview=spawn(npmCommand,["run","dev","--","--port",String(previewPort)],{cwd:frontend,stdio:"inherit",shell:process.platform==="win32"});
process.on("exit",()=>preview.kill());
const send=(r,s,v)=>{r.writeHead(s,{"Content-Type":"application/json; charset=utf-8"});r.end(JSON.stringify(v))};const body=async q=>{let a=[];for await(const x of q)a.push(x);return Buffer.concat(a)};const read=n=>readFile(join(data,n),"utf8").then(JSON.parse);
async function ship(){try{await exec("git",["add","frontend/public/data","frontend/public/images"],{cwd:root});try{await exec("git",["diff","--cached","--quiet"],{cwd:root});return{ok:true,message:"Nothing new to ship."}}catch{}await exec("git",["commit","-m","Update artwork collection via Studio"],{cwd:root});await exec("git",["push","origin","main"],{cwd:root});return{ok:true,message:"Shipped to GitHub. Vercel is deploying now."}}catch(e){return{ok:false,message:"Could not ship. Start Studio from Git Bash, then try again.",detail:e.stderr||e.message}}}
http.createServer(async(q,r)=>{let u=new URL(q.url,`http://${q.headers.host}`);try{if(q.method==="GET"&&u.pathname==="/"){r.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});let editor=await readFile(page,"utf8");editor+=`<script>const previewButton=document.createElement('button');previewButton.className='alt';previewButton.textContent='Preview website';previewButton.onclick=()=>window.open('http://localhost:${previewPort}','_blank');document.querySelector('.bar').insertBefore(previewButton,document.querySelector('.ship'));</script>`;return r.end(editor)}if(q.method==="GET"&&u.pathname==="/api/artworks")return send(r,200,await read("artworks.json"));if(q.method==="PUT"&&u.pathname==="/api/artworks"){await writeFile(join(data,"artworks.json"),JSON.stringify(JSON.parse((await body(q)).toString()),null,2)+"\n");return send(r,200,{ok:true})}if(q.method==="POST"&&u.pathname==="/api/upload"){let n=basename(q.headers["x-file-name"]||"artwork.jpg").replace(/[^\w.-]/g,"-"),b=await body(q);if(!(q.headers["content-type"]||"").startsWith("image/")||b.length>10485760)return send(r,400,{message:"Choose an image smaller than 10 MB."});await mkdir(images,{recursive:true});n=Date.now()+"-"+n+(extname(n)?"":".jpg");await writeFile(join(images,n),b);return send(r,201,{url:"/images/artworks/"+n})}if(q.method==="POST"&&u.pathname==="/api/ship")return send(r,200,await ship());send(r,404,{message:"Not found"})}catch(e){send(r,500,{message:e.message})}}).listen(port,"127.0.0.1",()=>console.log(`Anu Studio: http://localhost:${port} | Preview: http://localhost:${previewPort}`));
